Fix up theme to work with template updates
fishrules/changelog-generator pull request #1
Opened 2021-06-24 17:30 UTC by chrisbowley

Needs some clean up!

2021-06-24 20:23 UTC, rblalock requested changes
![Screen Shot 2021-06-24 at 4 19 18 PM](https://user-images.githubusercontent.com/211819/123327465-6ff95d00-d508-11eb-97aa-bb89d3181fe0.png)
![Screen Shot 2021-06-24 at 4 20 40 PM](https://user-images.githubusercontent.com/211819/123327472-7091f380-d508-11eb-9424-8fa9e35db323.png)
![Screen Shot 2021-06-24 at 4 21 12 PM](https://user-images.githubusercontent.com/211819/123327474-7091f380-d508-11eb-84a3-54692e4bf978.png)
![Screen Shot 2021-06-24 at 4 21 20 PM](https://user-images.githubusercontent.com/211819/123327476-712a8a00-d508-11eb-807b-daaa03ca7256.png)

Not sure why but it doesn't seem like the CSS is applied.

2021-06-24 20:23 UTC, rblalock commented on fr_theme/index.html
> -        </header>
There a reason to add this back in?

2021-06-25 09:10 UTC, chrisbowley commented
I cloned a fresh copy of this repo and re-tested this branch and everything seems fine. Here's what I did:

* Clone repo and cd into it
* `git checkout update`
* `npm I`
* Build the changelog using the custom there: `npm run build -- fishrules --theme-dir=./fr_theme`
* Run a local HTTP server to test: `cd dist && python -m SimpleHTTPServer 8080`
* Open browser at http://localhost:8080

2021-06-25 12:47 UTC, rblalock commented
`changelog-gen updates.fishrulesapp.com --theme-dir ./fr_theme --watch`

I was using this .. but i guess that doesn't work anymore?

2021-06-25 12:49 UTC, rblalock approved these changes

2021-06-25 13:03 UTC, merged